# Spotify API Credentials
spotify:
  client_id: "your_spotify_client_id_here"
  client_secret: "your_spotify_client_secret_here"

# AWS Credentials (if not using AWS CLI configuration)
aws:
  access_key_id: "your_aws_access_key_id_here"
  secret_access_key: "your_aws_secret_access_key_here"
  region: "your_preferred_region" # e.g., us-east-1

# S3 Configuration
s3:
  bucket_name: "your-spotify-data-bucket-name"
  raw_data_prefix: "raw/"
  processed_data_prefix: "processed/"
  models_prefix: "models/"

# Database Configuration (if needed)
database:
  host: "your_database_host"
  port: "your_database_port"
  name: "your_database_name"
  user: "your_database_user"
  password: "your_database_password"

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file_path: "logs/application.log"
