# Application Settings
app:
  name: "Spotify Data Pipeline"
  version: "1.0.0"
  environment: "development"  # development, staging, production

# Data Collection Settings
data_collection:
  batch_size: 50
  max_retries: 3
  retry_delay: 5  # seconds
  features_to_collect:
    - name
    - artist
    - album
    - release_date
    - popularity
    - duration_ms
    - explicit
    - danceability
    - energy
    - key
    - loudness
    - mode
    - speechiness
    - acousticness
    - instrumentalness
    - liveness
    - valence
    - tempo
    - time_signature

# Data Processing Settings
data_processing:
  min_popularity: 0
  max_popularity: 100
  normalize_features: true
  handle_missing_values: "mean"  # mean, median, mode, or drop
  remove_duplicates: true
  feature_engineering:
    create_year_feature: true
    create_month_feature: true
    create_day_feature: true

# Model Training Settings
model_training:
  test_size: 0.2
  random_state: 42
  cross_validation_folds: 5
  hyperparameter_tuning:
    n_trials: 100
    timeout: 3600  # seconds
  models:
    - name: "decision_tree"
      enabled: true
      params:
        max_depth: 10
        min_samples_split: 2
        min_samples_leaf: 1
    - name: "random_forest"
      enabled: true
      params:
        n_estimators: 100
        max_depth: 10
        min_samples_split: 2
    - name: "gradient_boosting"
      enabled: true
      params:
        n_estimators: 100
        learning_rate: 0.1
        max_depth: 3

# Model Evaluation Settings
model_evaluation:
  metrics:
    - mean_squared_error
    - root_mean_squared_error
    - mean_absolute_error
    - r2_score
  save_predictions: true
  generate_plots: true

# AWS Settings
aws:
  lambda:
    timeout: 900  # seconds
    memory_size: 1024  # MB
  glue:
    job_timeout: 3600  # seconds
    workers: 2
    worker_type: "G.1X"
  sagemaker:
    instance_type: "ml.m5.xlarge"
    max_runtime: 3600  # seconds

# Monitoring Settings
monitoring:
  enable_cloudwatch: true
  metrics_namespace: "SpotifyPipeline"
  log_level: "INFO"
  alert_email: ""  # Add email for alerts

# API Settings
api:
  base_url: "https://api.spotify.com/v1"
  timeout: 30  # seconds
  rate_limit:
    max_requests: 100
    time_window: 60  # seconds
